#include<stdio.h>

int main(void){
	unsigned long n,m;
	while(scanf("%lu", &n) != EOF){
		int i = 0;
		printf("Hailstone generated by %lu:\n", n);
		m = n;
		while(m != 1){
			printf("%lu ", m);
			if(m % 2 == 0)
				m = m / 2;
			else m = 3 * m + 1;
			i++;
		}
		printf("1\nNumber of hailstone generated:%d\n\n", i+1);
	}
	return 0;
}
